name: mineral_project
description: Build a powerful Discord applications in Dart
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  mineral:
    git:
      url: https://github.com/mineral-dart/core.git
      ref: develop

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
